on:
  release:
    types: [created]

name: Release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Update package.json
        run: |
          VERSION=${{ steps.get_release.outputs.tag_name }}
          jq --arg version "${VERSION//v/}" '.version=$version' package.json > package_tmp.json
          mv package_tmp.json package.json

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm ci

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./dist/browser/bundle.js
          asset_name: js-webauthn-browser.js
          asset_content_type: application/octet-stream
